---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
##### UBUNTU
  - name: ubuntu2204-01
    template_name: ubuntu-22-04
  - name: ubuntu2204-02
    template_name: ubuntu-22-04
  - name: ubuntu2204-03
    template_name: ubuntu-22-04
  - name: ubuntu2204-04
    template_name: ubuntu-22-04
  - name: ubuntu2204-05
    template_name: ubuntu-22-04
  - name: ubuntu2204-06
    template_name: ubuntu-22-04
  - name: ubuntu2204-07
    template_name: ubuntu-22-04
  - name: ubuntu2204-08
    template_name: ubuntu-22-04
  - name: ubuntu2204-09
    template_name: ubuntu-22-04
  - name: ubuntu2204-10
    template_name: ubuntu-22-04
#  - name: ubuntu2204-11
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-12
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-13
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-14
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-15
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-16
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-17
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-18
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-19
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-20
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-21
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-22
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-23
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-24
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-25
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-26
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-27
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-28
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-29
#    template_name: ubuntu-22-04
#  - name: ubuntu2204-30
#    template_name: ubuntu-22-04
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    destroy: ../default/destroy.yml
verifier:
  name: ansible
